package com.bulbview.recipeplanner.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class MainWindow extends CustomComponent {

    @AutoGenerated
    private VerticalLayout   mainLayout;
    @AutoGenerated
    private VerticalLayout   mainVerticalLayout;
    @AutoGenerated
    private GridLayout       shoppingList_gridLayout;
    @AutoGenerated
    private VerticalLayout   category3_verticalLayout;
    @AutoGenerated
    private VerticalLayout   category2_verticalLayout;
    @AutoGenerated
    private VerticalLayout   category1_verticalLayout;
    @AutoGenerated
    private Panel            panel_2;
    @AutoGenerated
    private VerticalLayout   verticalLayout_4;
    @AutoGenerated
    private HorizontalLayout RecipeAndSchedulerHorizontalLayout;
    @AutoGenerated
    private Accordion        SchedulerAccordion;
    @AutoGenerated
    private Panel            recipePanel;
    @AutoGenerated
    private VerticalLayout   recipePanelVerticalLayout;
    @AutoGenerated
    private HorizontalLayout TitleAndMenuLayout;
    @AutoGenerated
    private MenuBar          recipeplanner_menuBar;
    @AutoGenerated
    private HorizontalLayout logoHorizontalLayout;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public MainWindow() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    public void setApplicationLogo(final Embedded embedded) {
        embedded.setHeight("50px");
        logoHorizontalLayout.addComponent(embedded);
    }

    @AutoGenerated
    private VerticalLayout buildCategory1_verticalLayout() {
        // common part: create layout
        category1_verticalLayout = new VerticalLayout();
        category1_verticalLayout.setWidth("-1px");
        category1_verticalLayout.setHeight("-1px");
        category1_verticalLayout.setImmediate(false);
        category1_verticalLayout.setMargin(false);

        // category_label_1
        final Label category_label_1 = new Label();
        category_label_1.setWidth("31px");
        category_label_1.setHeight("-1px");
        category_label_1.setValue("Label");
        category_label_1.setImmediate(false);
        category1_verticalLayout.addComponent(category_label_1);

        // panel_2
        panel_2 = buildPanel_2();
        category1_verticalLayout.addComponent(panel_2);

        return category1_verticalLayout;
    }

    @AutoGenerated
    private VerticalLayout buildCategory2_verticalLayout() {
        // common part: create layout
        category2_verticalLayout = new VerticalLayout();
        category2_verticalLayout.setWidth("-1px");
        category2_verticalLayout.setHeight("-1px");
        category2_verticalLayout.setImmediate(false);
        category2_verticalLayout.setMargin(false);

        // category_label_2
        final Label category_label_2 = new Label();
        category_label_2.setWidth("-1px");
        category_label_2.setHeight("-1px");
        category_label_2.setValue("Label");
        category_label_2.setImmediate(false);
        category2_verticalLayout.addComponent(category_label_2);

        return category2_verticalLayout;
    }

    @AutoGenerated
    private VerticalLayout buildCategory3_verticalLayout() {
        // common part: create layout
        category3_verticalLayout = new VerticalLayout();
        category3_verticalLayout.setWidth("-1px");
        category3_verticalLayout.setHeight("-1px");
        category3_verticalLayout.setImmediate(false);
        category3_verticalLayout.setMargin(false);

        // category_label_3
        final Label category_label_3 = new Label();
        category_label_3.setWidth("-1px");
        category_label_3.setHeight("-1px");
        category_label_3.setValue("Label");
        category_label_3.setImmediate(false);
        category3_verticalLayout.addComponent(category_label_3);

        return category3_verticalLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildLogoHorizontalLayout() {
        // common part: create layout
        logoHorizontalLayout = new HorizontalLayout();
        logoHorizontalLayout.setWidth("-1px");
        logoHorizontalLayout.setHeight("50px");
        logoHorizontalLayout.setImmediate(false);
        logoHorizontalLayout.setMargin(false);

        return logoHorizontalLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // mainVerticalLayout
        mainVerticalLayout = buildMainVerticalLayout();
        mainLayout.addComponent(mainVerticalLayout);
        mainLayout.setComponentAlignment(mainVerticalLayout, new Alignment(20));

        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildMainVerticalLayout() {
        // common part: create layout
        mainVerticalLayout = new VerticalLayout();
        mainVerticalLayout.setWidth("699px");
        mainVerticalLayout.setHeight("404px");
        mainVerticalLayout.setImmediate(false);
        mainVerticalLayout.setMargin(false);

        // TitleAndMenuLayout
        TitleAndMenuLayout = buildTitleAndMenuLayout();
        mainVerticalLayout.addComponent(TitleAndMenuLayout);

        // RecipeAndSchedulerHorizontalLayout
        RecipeAndSchedulerHorizontalLayout = buildRecipeAndSchedulerHorizontalLayout();
        mainVerticalLayout.addComponent(RecipeAndSchedulerHorizontalLayout);
        mainVerticalLayout.setComponentAlignment(RecipeAndSchedulerHorizontalLayout, new Alignment(20));

        // ShoppingList_label
        final Label ShoppingList_label = new Label();
        ShoppingList_label.setWidth("-1px");
        ShoppingList_label.setHeight("-1px");
        ShoppingList_label.setValue("Shopping List");
        ShoppingList_label.setImmediate(false);
        mainVerticalLayout.addComponent(ShoppingList_label);

        // shoppingList_gridLayout
        shoppingList_gridLayout = buildShoppingList_gridLayout();
        mainVerticalLayout.addComponent(shoppingList_gridLayout);
        mainVerticalLayout.setComponentAlignment(shoppingList_gridLayout, new Alignment(48));

        return mainVerticalLayout;
    }

    @AutoGenerated
    private Panel buildPanel_2() {
        // common part: create layout
        panel_2 = new Panel();
        panel_2.setWidth("100px");
        panel_2.setHeight("30px");
        panel_2.setImmediate(false);

        // verticalLayout_4
        verticalLayout_4 = buildVerticalLayout_4();
        panel_2.setContent(verticalLayout_4);

        return panel_2;
    }

    @AutoGenerated
    private HorizontalLayout buildRecipeAndSchedulerHorizontalLayout() {
        // common part: create layout
        RecipeAndSchedulerHorizontalLayout = new HorizontalLayout();
        RecipeAndSchedulerHorizontalLayout.setWidth("100.0%");
        RecipeAndSchedulerHorizontalLayout.setHeight("-1px");
        RecipeAndSchedulerHorizontalLayout.setImmediate(false);
        RecipeAndSchedulerHorizontalLayout.setMargin(true);
        RecipeAndSchedulerHorizontalLayout.setSpacing(true);

        // recipePanel
        recipePanel = buildRecipePanel();
        RecipeAndSchedulerHorizontalLayout.addComponent(recipePanel);

        // SchedulerAccordion
        SchedulerAccordion = new Accordion();
        SchedulerAccordion.setWidth("300px");
        SchedulerAccordion.setHeight("200px");
        SchedulerAccordion.setImmediate(false);
        RecipeAndSchedulerHorizontalLayout.addComponent(SchedulerAccordion);
        RecipeAndSchedulerHorizontalLayout.setComponentAlignment(SchedulerAccordion, new Alignment(6));

        return RecipeAndSchedulerHorizontalLayout;
    }

    @AutoGenerated
    private Panel buildRecipePanel() {
        // common part: create layout
        recipePanel = new Panel();
        recipePanel.setWidth("300px");
        recipePanel.setHeight("200px");
        recipePanel.setImmediate(false);

        // recipePanelVerticalLayout
        recipePanelVerticalLayout = buildRecipePanelVerticalLayout();
        recipePanel.setContent(recipePanelVerticalLayout);

        return recipePanel;
    }

    @AutoGenerated
    private VerticalLayout buildRecipePanelVerticalLayout() {
        // common part: create layout
        recipePanelVerticalLayout = new VerticalLayout();
        recipePanelVerticalLayout.setWidth("100.0%");
        recipePanelVerticalLayout.setHeight("100.0%");
        recipePanelVerticalLayout.setImmediate(false);
        recipePanelVerticalLayout.setMargin(false);

        return recipePanelVerticalLayout;
    }

    @AutoGenerated
    private GridLayout buildShoppingList_gridLayout() {
        // common part: create layout
        shoppingList_gridLayout = new GridLayout();
        shoppingList_gridLayout.setWidth("100.0%");
        shoppingList_gridLayout.setHeight("100px");
        shoppingList_gridLayout.setImmediate(false);
        shoppingList_gridLayout.setMargin(false);
        shoppingList_gridLayout.setColumns(3);
        shoppingList_gridLayout.setRows(3);

        // category1_verticalLayout
        category1_verticalLayout = buildCategory1_verticalLayout();
        shoppingList_gridLayout.addComponent(category1_verticalLayout, 0, 0);
        shoppingList_gridLayout.setComponentAlignment(category1_verticalLayout, new Alignment(48));

        // category2_verticalLayout
        category2_verticalLayout = buildCategory2_verticalLayout();
        shoppingList_gridLayout.addComponent(category2_verticalLayout, 1, 0);
        shoppingList_gridLayout.setComponentAlignment(category2_verticalLayout, new Alignment(48));

        // category3_verticalLayout
        category3_verticalLayout = buildCategory3_verticalLayout();
        shoppingList_gridLayout.addComponent(category3_verticalLayout, 2, 0);
        shoppingList_gridLayout.setComponentAlignment(category3_verticalLayout, new Alignment(48));

        return shoppingList_gridLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildTitleAndMenuLayout() {
        // common part: create layout
        TitleAndMenuLayout = new HorizontalLayout();
        TitleAndMenuLayout.setWidth("-1px");
        TitleAndMenuLayout.setHeight("-1px");
        TitleAndMenuLayout.setImmediate(false);
        TitleAndMenuLayout.setMargin(false);

        // logoHorizontalLayout
        logoHorizontalLayout = buildLogoHorizontalLayout();
        TitleAndMenuLayout.addComponent(logoHorizontalLayout);

        // recipeplanner_menuBar
        recipeplanner_menuBar = new MenuBar();
        recipeplanner_menuBar.setWidth("750px");
        recipeplanner_menuBar.setHeight("50px");
        recipeplanner_menuBar.setImmediate(false);
        TitleAndMenuLayout.addComponent(recipeplanner_menuBar);

        return TitleAndMenuLayout;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_4() {
        // common part: create layout
        verticalLayout_4 = new VerticalLayout();
        verticalLayout_4.setWidth("100.0%");
        verticalLayout_4.setHeight("100.0%");
        verticalLayout_4.setImmediate(false);
        verticalLayout_4.setMargin(false);

        return verticalLayout_4;
    }

}
