package com.bulbview.recipeplanner.ui;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

@Component
public class RecipeEditor extends CustomComponent {
    
    @AutoGenerated
    private VerticalLayout   mainLayout;
    @AutoGenerated
    private Button           saveButton;
    @AutoGenerated
    private TextArea         notesField;
    @AutoGenerated
    private HorizontalLayout ingredientsSelectionLayout;
    @AutoGenerated
    private Accordion        categoriesAccordion;
    @AutoGenerated
    private Table            ingredientsTable;
    @AutoGenerated
    private TextField        recipeNameField;
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    @Autowired
    private Window           recipeWindow;
    
    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization. The constructor will not be
     * automatically regenerated by the visual editor.
     */
    public RecipeEditor() {
        buildMainLayout();
        setCompositionRoot(mainLayout);
        
        // TODO add user code here
    }
    
    public Accordion getCategoryAccordion() {
        return categoriesAccordion;
    }
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    
    public TextField getRecipeNameField() {
        return recipeNameField;
    }
    
    public Button getSaveButton() {
        return saveButton;
    }
    
    public void init() {
        initRecipeWindowComponents();
    }
    
    public void showErrorMessage(String message) {
        getWindow().showNotification(message);
    }
    
    @AutoGenerated
    private HorizontalLayout buildIngredientsSelectionLayout() {
        // common part: create layout
        ingredientsSelectionLayout = new HorizontalLayout();
        ingredientsSelectionLayout.setImmediate(false);
        ingredientsSelectionLayout.setWidth("-1px");
        ingredientsSelectionLayout.setHeight("-1px");
        ingredientsSelectionLayout.setMargin(false);
        ingredientsSelectionLayout.setSpacing(true);
        
        // ingredientsTable
        ingredientsTable = new Table();
        ingredientsTable.setImmediate(false);
        ingredientsTable.setWidth("300px");
        ingredientsTable.setHeight("300px");
        ingredientsSelectionLayout.addComponent(ingredientsTable);
        
        // categoriesAccordion
        categoriesAccordion = new Accordion();
        categoriesAccordion.setImmediate(false);
        categoriesAccordion.setWidth("300px");
        categoriesAccordion.setHeight("300px");
        ingredientsSelectionLayout.addComponent(categoriesAccordion);
        
        return ingredientsSelectionLayout;
    }
    
    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("-1px");
        mainLayout.setMargin(true);
        mainLayout.setSpacing(true);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("-1px");
        
        // recipeNameField
        recipeNameField = new TextField();
        recipeNameField.setImmediate(false);
        recipeNameField.setWidth("300px");
        recipeNameField.setHeight("-1px");
        recipeNameField.setInputPrompt("<Enter Recipe Name>");
        recipeNameField.setSecret(false);
        mainLayout.addComponent(recipeNameField);
        
        // ingredientsSelectionLayout
        ingredientsSelectionLayout = buildIngredientsSelectionLayout();
        mainLayout.addComponent(ingredientsSelectionLayout);
        
        // notesField
        notesField = new TextArea();
        notesField.setImmediate(false);
        notesField.setDescription("Recipe notes");
        notesField.setWidth("606px");
        notesField.setHeight("-1px");
        notesField.setInputPrompt("<enter any notes>");
        notesField.setMaxLength(600);
        notesField.setNullRepresentation("no notes");
        mainLayout.addComponent(notesField);
        
        // saveButton
        saveButton = new Button();
        saveButton.setCaption("Save");
        saveButton.setImmediate(true);
        saveButton.setWidth("-1px");
        saveButton.setHeight("-1px");
        mainLayout.addComponent(saveButton);
        
        return mainLayout;
    }
    
    private void initRecipeWindowComponents() {
        recipeWindow.setWidth("75%");
        recipeWindow.setHeight("75%");
        recipeWindow.addComponent(this);
    }
    
}
